### ISSUE TITLE
I am getting  error Could not load model microsoft/DialoGPT-large e

### ISSUE THREAD

**Issue by tarkanlar** [golivecosmos/llm-react-node-app-template#9]
Äpp is starting on port: 3100
  <-- POST /chat
  xxx POST /chat 500 706ms -

  Error: Could not load model microsoft/DialoGPT-large with any of the following classes: (<class 'transformers.models.gpt2.modeling_gpt2.GPT2LMHeadModel'>, <class 'transformers.models.gpt2.modeling_tf_gpt2.TFGPT2LMHeadModel'>).
      at request (file:///Users/t/dev/llm-react-node-app-template/node_modules/@huggingface/inference/dist/index.mjs:106:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async conversational (file:///Users/t/dev/llm-react-node-app-template/node_modules/@huggingface/inference/dist/index.mjs:448:15)
      at async HuggingFaceService.call (file:///Users/t/dev/llm-react-node-app-template/server/services/hf.js:17:24)
      at async ChatService.startChat (file:///Users/t/dev/llm-react-node-app-template/server/handlers/chat_handler.js:10:22)
      at async file:///Users/t/dev/llm-react-node-app-template/server/routers/chat.js:16:15
      at async cors (/Users/t/dev/llm-react-node-app-template/node_modules/@koa/cors/index.js:108:16)
      at async logger (/Users/t/dev/llm-react-node-app-template/node_modules/koa-logger/index.js:67:7)

**Comment by katrinar** [comment]
Hi @tarkanlar, thanks for filing an issue. 

Looks like you are using a HuggingFace model. Can you confirm that you have the `ENABLED_MODEL_STORE` and `HUGGINGFACEHUB_API_KEY` environment variables set up? For `ENABLED_MODEL_STORE` it should be set to `HUGGING_FACE`.
